### ISSUE TITLE
Change QueryRequest.panelId to int64

### ISSUE THREAD

**Issue by BertholdBredenkamp** [andig/gravo#12]
I used the "json over http" Adapter and got this error message:
json decode failed: json: cannot unmarshal number 23763571993 into Go struct field QueryRequest.panelId of type int

After changing the line 70 of gravo/grafana/model.go to : PanelID       int64           `json:"panelId"`  its ok.

Thanks for your work
Berthold

**Comment by andig** [comment]
Fixed in https://github.com/andig/gravo/commit/582082ff89ff40ef566179d29f8f07b5eb72aa4d, thanks for the hint!
