### ISSUE TITLE
json decode failed: json: cannot unmarshal string into Go struct field Target.targets.data of type grafana.TargetData

### ISSUE THREAD

**Issue by vbartels** [andig/gravo#16]
Hi,
I can see gravo getting the metrics. All channels I have in VZ appear. But if I choose one I get
`
"2021/05/05 18:23:17 json decode failed: json: cannot unmarshal string into Go struct field Target.targets.data of type grafana.TargetData"`

I also tried demo.volkszaehler.org, See all the channels from there, too but no data.

**Comment by vbartels** [comment]
Additional Info:
it works with Simple JSON but not with JSON Datasource.

**Comment by lindstroem165** [comment]
![grafik](https://user-images.githubusercontent.com/84097336/118023794-40c6cc00-b35e-11eb-8163-ef155e2f5f13.png)
Same here - Similar Output for you?

**Comment by Pele1978** [comment]
Hello,

I'm using this great tool since a long time as well, but by updating grafana to latest version I'm getting the same error message. Is there a solution available meanwhile?

Thanks

Pele1978

**Comment by neuhausf** [comment]
I fixed this in my fork: https://github.com/andig/gravo/compare/master...neuhausf:gravo:master
@andig Feel free to enhance and merge ;)

**Comment by lindstroem165** [comment]
![grafik](https://user-images.githubusercontent.com/84097336/200075590-1b8a5e11-9260-4ed2-80ae-a3c59e4611f1.png)
i get compilation errors? Only me?

**Comment by lindstroem165** [comment]
`server.go:288:3: pr declared but not used (typecheck)
                pr, err := server.api.QueryPrognosis(target.Target, target.Payload.Period)
                ^
make: *** [Makefile:15: lint] Error 1`
@neuhausf: I have "go version go1.19.3 linux/arm". You have an idea?

**Comment by neuhausf** [comment]
@lindstroem165 I didn‘t compile it myself - I used the github action to generate a docker image (which is public).

**Comment by lindstroem165** [comment]
Unfortunalety, I haven't used that before and for me it results in errors :(
`The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
exec /usr/bin/gravo: exec format error`
I think i will debug and try to compile it locally - I have at least slightly more experience there than with github actions :D

**Comment by andig** [comment]
Should be fixed by https://github.com/andig/gravo/pull/17
