### ISSUE TITLE
json decode failed: http: read on closed response body

### ISSUE THREAD

**Issue by grseidel** [andig/gravo#2]
golang version  7 and 11.5 tested.
called by gravo -api http://localhost//middleware.php -url localhost:8001 (the -port option mentioned in the README does not seem to exist (anymore)).
Using the -verbose option prints a copy of the json received and gets stuck without the above error.
`{"version":"0.3","entities":[{"uuid":"7974cb80-21fc-11e9-bcf8-e98c4b5c7235","type":"powersensor","color":"#2e7d32","fillstyle":0,"public":true,"style":"steps","title":"SDM630_modbus_p1","yaxis":"auto"},{"uuid":"9736f8d0-21fc-11e9-a5b0-61a54f50b194","type":"powersensor","color":"#e64a19","fillstyle":0,"public":true,"style":"steps","title":"SDM630_modbus_p3","yaxis":"auto"},{"uuid":"9ab9d9f0-21fc-11e9-a9a4-4d60f1c1eda1","type":"powersensor","color":"#fdd835","fillstyle":0,"public":true,"style":"steps","title":"SDM630_modbus_p2","yaxis":"auto"},{"uuid":"e462af00-21fc-11e9-8f35-73f26c7d5a33","type":"powersensor","color":"#0d47a1","fillstyle":0,"public":true,"style":"steps","title":"SDM630_modbus","yaxis":"auto"},{"uuid":"533ce600-21ff-11e9-88fe-a1d47d8100e0","type":"voltage","color":"aqua","fillstyle":0,"public":true,"style":"lines","title":"LiFePo4","yaxis":"auto"},{"uuid":"a8c07e60-2207-11e9-b808-fdbc13daa069","type":"powersensor","color":"#8e24aa","fillstyle":0,"public":true,"style":"steps","title":"SDM630_S0_A","yaxis":"auto"},{"uuid":"49a7cf40-220a-11e9-85c1-25673e1967f9","type":"powersensor","color":"#78909c","fillstyle":0,"public":true,"style":"steps","title":"SDM630_S0_B","yaxis":"auto"},{"uuid":"a39b2040-2217-11e9-bebb-adac00d601e3","type":"powersensor","color":"#ef9a9a","fillstyle":0,"public":true,"style":"steps","title":"DRT428DC_S0","yaxis":"auto"}]}
` 
(I know this includes my UUIDs but I have an offline installation ;-)
I any case Grafana responds with "HTTP error bad request".

**Comment by andig** [comment]
Could you check if this was introduced by the latest commit?

**Comment by grseidel** [comment]
I tried the penultimate commit and two others: 
3859799b9c7f5f8e022c2eb7cec58bfa2c6c6ec8
025179191cae970dc82dd3dd921face68c0e90bb
bef5b2e05df7d28e48d7eb405f7b239f5fe30ba0
All to the same result.
Thanks.
Rgds.
GES

**Comment by andig** [comment]
Btw, your api url looks wrong:

>  -api http://localhost//middleware.php

**Comment by andig** [comment]
I've just pushed another commit- should be fixed now.

**Comment by grseidel** [comment]
Works now. Thank you!
