### ISSUE TITLE
Idee: Namensvergebung

### ISSUE THREAD

**Issue by ArwedM** [andig/gravo#3]
Hallo,
da ich die Daten mit der Channel UUID vom Volkszähler anfordere, steht die UUID auch im Namen des Kanals von Grafana. Unter der UUID können andere Nutzer des Grafana Webservers aber nicht wissen welcher Kanal damit gemeint ist. 

Nun mein Vorschlag:
Man kann ja in Grafana noch "Additional JSON Data" einfügen, dort könnte man unterdem tag "name" einen Kanalnamen einfügen, welcher einfach als "target" in der respone zurückgegeben wird.

Hier habe ich schonmal meine Aktuelle Löseung (einfach im script "server.go" in der Zeile 201 einfügen):
> if name, ok := target.Data["name"]; ok {
> &emsp;qres.Target = name
> }

Zusätzlich wird noch (wie oben schon erwähnt) in der Grafana Datenabfrage ("Metrics") bei dem Gewünschten Kanal in "Additional JSON Data" der Name für den Kanal im JSON format benötigt. Beispiel:
> {"name": "Außentemperatur"}

Arwed

**Comment by andig** [comment]
Keine schlechte Idee, müsste aber auch dokumentiert werden. Alternativ könnte man schlicht auch immer den Namen ins Target schreiben. Grafana scheint die Ergebnisse nämlich schlicht in Reihenfolge zu verarbeiten?

**Comment by andig** [comment]
Btw, I'm selecting my channels by name and do not have this problem:

<img width="555" alt="screenshot 2019-02-10 at 11 43 48" src="https://user-images.githubusercontent.com/184815/52532679-35bd0580-2d29-11e9-92b9-52f941cc81d2.png">

Would selecting by name also work for you?

**Comment by ArwedM** [comment]
Ja es funktioniert, bei Kanalnamen mit eindeutigem namen, wenn ich aber zwei Kanäle mit dem gleichen namen habe kann ich nicht explizit sagen welchen Kanal ich angezeigt haben möchte. Oder wenn ich die Temperatur im Schlaf- und Wohnzimmer messen möchte, heißt ein Kanal "Schlafzimmer Temperatur" und der andere "Wohnzimmer Temperatur", diese beiden Kanäle stelle ich jetzt in einem Grafen da um den es nur im die Temperatur geht, dann ist es nicht so schön, wenn bei beiden noch Temperatur dahinter steht.

**Comment by ArwedM** [comment]
Da fällt mir auch noch ein, dass ich mit den namen nur die öffentlichen Kanäle abfragen kann. mit der UUID kann ich auch private abfragen.

**Comment by andig** [comment]
Magst Du einen PR einstellen?

**Comment by ArwedM** [comment]
Habe ich es richtig gemacht? ist mein erstes mal...

**Comment by andig** [comment]
Nope- ist nix angekommen. Du musst der PR noch bei Github gegen dieses Repo erstellen.

**Comment by andig** [comment]
Das hab ich grad für Dich gemacht- Änderungen in eigenem Branch war schonmal top. Magst Du auch noch die Readme aktualisieren?

**Comment by ArwedM** [comment]
Danke
Ist es so gut?
