### ISSUE TITLE
Ergänzungsvorschlag: Doku

### ISSUE THREAD

**Issue by grseidel** [andig/gravo#5]
Hallo,

die Verwendung des Feldes "Additional JSON Data" in Grafana bei der Abfrage von Gravo finde ich etwas wenig dokumentiert, habe es mir z.T. aus dem Quelltext erschliessen können und würde vorschlagen das in der README zu ergänzen, z.B:

example
`{"group": "day", "options": "raw", "context": "prognosis", "name": "Channel Name"}`

5.2 optional: If you use the UUID it's recommended to change the target name by adding the above line to "Additional JSON Data"

5.3 optional: group allows to aggregate data for each hour, day or month. Can be used to generate summary bar charts

5.4 optional: options are forwarded to the vz middleware, currently supported there is only "raw" to provide the raw data from the database (i.e. no pulse to power convertion)

5.5 optional: "context": "prognosis" ... (habe ich nicht verstanden :-x )

Gibt es eine Möglichkeit Energieverbräuche abzufragen wie es ja auch das vz-frontend darstellt? Im einfachsten Fall für den Tagesverbrauch wäre ja eigentlich nur das Ergebnis von {"group": "day"} * 24 - irgendwie bekomme ich das aber in Grafana/gravo nicht umgesetzt...

Gruss
GES

**Comment by andig** [comment]
Mach gerne einen PR. 

Die Daten werden einfach nur als Parameter zum Bau der Middleware URL benutzt. Insofern bekommst Du Verbrauch auch (falls next branch) mit `options=consumption`. Der `context` ist ebenfalls genau das was er bei der Middleware bedeutet, siehe VZ Wiki- typischerweise `data` für Daten.

**Comment by grseidel** [comment]
PR habe ich erstellt.
context habe ich weggelassen, da ich keine Reaktion erzeugen konnte.
Danke! Gruss GES

**Comment by andig** [comment]
> PR habe ich erstellt.

ich seh leider keinen?

**Comment by grseidel** [comment]
Sorry, hatte einen branch erstellt ohne Dir die Anfrage zum Merge zu stellen. Sollte jetzt gehen.
PS: Den Tip bzgl. consumption im VZ next sehe ich mir noch an, bin derzeit noch nicht auf next.
Gruss
GES
