### ISSUE TITLE
Rechnen in Additional JSON Data?

### ISSUE THREAD

**Issue by emeins** [andig/gravo#7]
Ist es möglich in dem "Additional JSON Data" Feld zu rechnen? Wenn ich {"group":"day"} angebe, liefert er bei den Leistungswerten den Tagesdurchschnittswert in Watt/Stunde, ich bräuchte aber den Tageswert, also x 24.

**Comment by andig** [comment]
Du brauchst volkszaehler next und dann zusätzlich options=consumption für die Metrik. 

Viele Grüße,
Andreas

**Comment by emeins** [comment]
Ein Docker Container für next wäre nett. ;-)

**Comment by andig** [comment]
yo, ist in arbeit. prs welcome...
